### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by davemlz** [giswqs/geospatial-ml#2]
Hi Prof. Wu,

Here are some suggestions for this package:

Frameworks:
- `tensorflow`
- `keras`
- `pytorch`
- `pytorch-lightning`

Modules
- `scikit-gstat`

Visualization
- `scikit-plot`

**Comment by giswqs** [comment]
Thanks for the suggestions. Will work on this once the package is available on conda-forge.

**Comment by RichardScottOZ** [comment]
Pyspatialml?

**Comment by giswqs** [comment]
@RichardScottOZ Pyspatialml is not available on [conda-forge](Pyspatialml). It needs to be available on both PyPI and conda-forge before it can be added to geospatial-ml.

**Comment by giswqs** [comment]
@davemlz All suggested packages have been added. Thanks for the suggestions.
