### ISSUE TITLE
Suggestions for adding packages to geospatial-ml

### ISSUE THREAD

**Issue by giswqs** [giswqs/geospatial-ml#3]
If you would like to suggest new packages to be added to the geospatial stack, please leave comments down here. Here are the steps:

First, check https://ml.gishub.org/#installed-packages and see if the suggested packages are listed on the list. If they are already listed, then you can skip the following steps.

Second, search the suggested packages on https://conda-forge.org/feedstock-outputs and make sure they can be found there. If not, that means the suggested packages are not available on conda-forge. If this is the case, then they cannot be added to the geospatial stack. Then you can skip the following step.

Third, leave the names of suggested packages here if they meet the above requirements.

**Comment by eecheonwu** [comment]
Deep graph library DGL would be a great add.

**Comment by giswqs** [comment]
@eecheonwu It appears that [DGL](https://anaconda.org/dglteam/dgl) is not available on [conda-forge](https://conda-forge.org/feedstock-outputs/). Conda forge receipt does not allow packages from custom conda channels. See https://github.com/conda/conda-build/issues/532

**Comment by davemlz** [comment]
Hi Prof. Wu,

I just found this one: [`eo-learn`](https://github.com/sentinel-hub/eo-learn). I've never used it but seems quite interesting and it has a big user-base.

**Comment by fsn1995** [comment]
Thank you so much for your excellent work! Maybe vaex (It is a meta package https://vaex.io/docs/installing.html) could be useful for visualizing and exploring big tabular datasets?

**Comment by giswqs** [comment]
@fsn1995 I have added vaex. It appears that vaex does not support Python 3.10 yet. See https://github.com/vaexio/vaex/issues/1951

The conda-forge [recipe](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=494154&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1629) fails to build for Python 3.10. I am not sure how to resolve it yet.

**Comment by cmg777** [comment]
Thank you for your excellent work! 
After confirming step1 and stetp2, I would like to suggest the following spatial packages:

- [splot](https://anaconda.org/conda-forge/splot)
- [mgwr](https://anaconda.org/conda-forge/mgwr)
- [esda](https://anaconda.org/conda-forge/esda)
- [spreg](https://anaconda.org/conda-forge/spreg)
- [mapclassify](https://anaconda.org/conda-forge/mapclassify)
- [inequality](https://anaconda.org/conda-forge/inequality)

These packages are from the PySAL library and they are very much used in the social sciences.

**Comment by giswqs** [comment]
@cmg777 Good suggestions. I will work on it this weekend.

**Comment by giswqs** [comment]
@cmg777 The suggested packages will be added once the pysal issue has been resolved. See 
https://github.com/pysal/pointpats/issues/80

**Comment by cmg777** [comment]
Got it. Thanks you very much for your great work.

**Comment by giswqs** [comment]
@fsn1995  Unfortunately, `vaex` does not yet support Python 3.10. It can't be added to the conda-forge package at the moment. I will revisit it later when it supports Python 3.10. 

https://github.com/conda-forge/geospatial-ml-feedstock/pull/5
![image](https://user-images.githubusercontent.com/5016453/164862578-3180aca6-cd53-4aea-9677-425ad1d12c38.png)
